### ISSUE TITLE
Loopable Animations

### ISSUE THREAD

**Issue by 9helix** [NikhilVadoliya/FlutterAnimatedButton#6]
**Describe the solution you'd like**
Current animations make it look like the button's state is either toggled on or off. But what if I have the button that, for example, prints the number of times it was pressed? I wouldn't want it to look like its toggled. I'd want the button to look the same before and after the animation.

**Additional context**
Something like this from your documentation. Buttons look the same at the beginning and at the end of the GIF.
![banner_1 0 0_2](https://user-images.githubusercontent.com/62692130/162590422-333d5648-5224-4959-b1df-12de5155bb25.gif)

**Comment by NikhilVadoliya** [comment]
Hello @9helix, Thanks your feedback, this plugin purpose only toggle type feature or selection type as you can see in  [#User in App](https://pub.dev/packages/flutter_animated_button#used-in-app)


In Documentation GIF, there covered normal->selected->normal state of button that's why display same at the beginning and at the end of the GIF.


So this is not issue in plugin
